# -*- coding: utf-8 -*-
"""IMDB sentimental analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8DI-AjBWmy9bdcHz5h9eWkDdGwUlyGo
"""

import numpy as np
import tensorflow_datasets as tfds
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Load the IMDb dataset
train_data, test_data = tfds.load(name="imdb_reviews", split=["train", "test"], batch_size=-1, as_supervised=True)

# Convert to NumPy arrays
train_examples, train_labels = tfds.as_numpy(train_data)

# Filter for positive sentiment reviews (label 1)
positive_reviews = train_examples[train_labels == 1]

# Join all the positive reviews into a single string
positive_text = " ".join([str(review) for review in positive_reviews])

# Generate the word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(positive_text)

# Plot the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")  # Hide the axes
plt.title('Word Cloud for Positive Sentiment Reviews')
plt.show()

import numpy as np
import tensorflow_datasets as tfds
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Load the IMDb dataset
train_data, test_data = tfds.load(name="imdb_reviews", split=["train", "test"], batch_size=-1, as_supervised=True)

# Convert to NumPy arrays
train_examples, train_labels = tfds.as_numpy(train_data)

# Filter for positive and negative sentiment reviews
positive_reviews = train_examples[train_labels == 1]
negative_reviews = train_examples[train_labels == 0]

# Join all the positive reviews into a single string
positive_text = " ".join([str(review) for review in positive_reviews])

# Join all the negative reviews into a single string
negative_text = " ".join([str(review) for review in negative_reviews])

# Generate the word cloud for positive reviews
positive_wordcloud = WordCloud(width=800, height=400, background_color='white').generate(positive_text)

# Generate the word cloud for negative reviews
negative_wordcloud = WordCloud(width=800, height=400, background_color='white').generate(negative_text)

# Plot the word cloud for positive sentiment
plt.figure(figsize=(10, 5))
plt.imshow(positive_wordcloud, interpolation='bilinear')
plt.axis("off")  # Hide the axes
plt.title('Word Cloud for Positive Sentiment Reviews')
plt.show()

# Plot the word cloud for negative sentiment
plt.figure(figsize=(10, 5))
plt.imshow(negative_wordcloud, interpolation='bilinear')
plt.axis("off")  # Hide the axes
plt.title('Word Cloud for Negative Sentiment Reviews')
plt.show()

